### PR TITLE
Modernize library

### PR DESCRIPTION
**Pull request by shawnmcknight**
This PR completely updates the library to support React >= 16.8.0.  Essentially everything has been rewritten from the ground up.  The repo has been converted from JavaScript to TypeScript, all of the tooling has been refreshed and updated, and the component is now a functional component using React hooks.

** Breaking Changes **
The API for the component has changed.  It no longer accepts both `onChange` and `onLoad` props, instead only using a single `onChange` prop which serves both purposes.  Additionally, the `onChange` callback no longer accepts an object with property names `scrollbarHeight` and `scrollbarWidth`, instead using the shorter `height` and `width`.

### CODE REVIEW

**Comment by kgregory** [comment]
Nice job

**Comment by Noitidart** [comment]
This is awesome, do you have plans for a hook for this?

**Comment by kgregory** [comment]
@Noitidart I was toying with that idea.  I may submit a PR

**Comment by Noitidart** [comment]
Thank you for your awesome work and help to the community! I want to PR this thing to use your library because I dont think it handles adjust on zoom. https://github.com/theKashey/react-remove-scroll-bar

**Comment by kgregory** [comment]
I've whipped up a quick test to see if I could create such a hook: https://codesandbox.io/s/react-scrollbar-size-hook-mw6pf

Take a look.

Since our method of measuring the scrollbar in the component involves adding an element to the DOM, this hook would have to do the same.  Not really a problem if it cleans up after itself.

The benefit of the hook is that it requires _way_ less from the consumer.  Since it manages its own state, consumers can simply invoke the hook to access the scrollbar `height` and `width`.

Any objections to adding a hook to supplement the component, @shawnmcknight?

**Comment by shawnmcknight** [comment]
> Any objections to adding a hook to supplement the component, @shawnmcknight?

No objections at all.  I guess we would export both the component and the hook for use?  I think as long as we make sure to reuse as much code as possible in both places to maintain consistency this would be a very good update.

**Pull request merged**
